name: Image test

on:
  push:
    branches:
      - master

jobs:
  docker-run:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build --tag=backend:latest .
      - name: Run image
        run: docker run -d -p 4001:4001 backend:latest
      - name: Add permission
        run: chmod +x check-port.sh
      - name: Verify port
        run: ./check-port.sh


